#!/bin/bash

# options: "local" (github repository) | "binary" (pyinstaller distribution)
EXECUTABLE="local"

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BINARY_PATH="${SCRIPT_DIRECTORY}/somax_server/somax_server"
LOCAL_PATH="${SCRIPT_DIRECTORY}/../../../python/somax/somax2_server.py"


run_local() {
    echo -e "\033[1m[INFO]: Launching Somax server (local installation)...\033[0m"
    "$LOCAL_PATH"
}

run_binary() {
    "$BINARY_PATH"
    retval=$?
    if (($retval == 0 )) || (( $retval == 130 )); 
    then 
        exit 0; 
    else
        echo -e "\033[1m[FATAL]: Could not run server.\033[0m"
        exit 1
    fi
}

if [ "$EXECUTABLE" = "local" ]
then
    run_local
    retval=$?
    if (($retval == 0 )) || (( $retval == 130 )); 
    then 
        exit 0; 
    # Temporary modification while PyInstaller isn't working.
    else
        exit $retval;
    # else
    #     echo -e "\033[1m[FATAL]: Could not run local installation of server. Attempting to launch pre-compiled binary...\033[0m"
    #     run_binary
    fi
elif [ "$EXECUTABLE" = "binary" ]
then
    # run_binary
    echo -e "\033[1m[FATAL]: Option \"${EXECUTABLE}\" is currently not supported. Terminating application.\033[0m"
else
    echo -e "\033[1m[FATAL]: Unknown option \"${EXECUTABLE}\". Ensure that \$EXECUTABLE is set to one of the valid options in file ${BASH_SOURCE[0]}.\033[0m"
    
fi
